---
title: "graphs"
author: "Graham Dynis"
date: "2024-09-18"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(stats)
library(ggplot2)
library(readr)
library(dplyr)
library(reshape2)
library(scales)
```

```{r}
df_train = read.csv('df_train.csv')
cat("Training Data Types:\n")
str(df_train)
```

```{r}
df_train <- df_train %>%
  mutate(month_year_index = (year - 2011) * 12 + month)
df_train <- df_train %>%
  mutate(month_year_index = month_year_index - min(month_year_index) + 1)
head(df_train[, c("year", "month", "month_year_index")])
```

```{r}
df_summary <- df_train %>%
  group_by(month_year_index, state_id) %>%
  summarise(total_sales = sum(sales, na.rm = TRUE))
```

```{r}
df_train <- df_train %>%
  mutate(month_year_label = paste(month, year, sep = "-"))
```

```{r}
df_labels <- df_train %>%
  select(month_year_index, month_year_label) %>%
  distinct()
```

```{r}
breaks_6_months <- seq(1, max(df_summary$month_year_index), by = 6)
break_labels <- df_labels %>%
  filter(month_year_index %in% breaks_6_months)
```

```{r}
ggplot(df_summary, aes(x = month_year_index, y = total_sales, color = state_id, group = state_id)) +
  geom_line(size = 1) +
  labs(title = "Sum of Sales by Month-Year for Each State",
       x = "Month-Year",
       y = "Total Sales") +
  theme_minimal() +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_continuous(
    breaks = breaks_6_months,
    labels = break_labels$month_year_label
  )
```

```{r}
df_summary2 <- df_train %>%
  group_by(month_year_index, cat_id) %>%
  summarise(mean_sell_price = mean(sell_price, na.rm = TRUE))
```

```{r}
ggplot(df_summary2, aes(x = month_year_index, y = mean_sell_price, color = cat_id, group = cat_id)) +
  geom_line(size = 1) +
  labs(title = "Mean Sell Price by Category (cat_id) Over Time",
       x = "Month-Year Index",
       y = "Mean Sell Price") +
  theme_minimal() +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_continuous(breaks = breaks_6_months,
                     labels = break_labels$month_year_label)
```

```{r, include=TRUE}
df_state = df_train %>% group_by(state_id) %>% summarise(total_sales = sum(sales))
df_state_ave = df_train %>% group_by(state_id) %>% summarise(avg_sales = mean(sales))
```

```{r, include=TRUE}
require(scales)
#Graph
ggplot(data = df_state, aes(x=state_id, y=total_sales, fill=state_id)) + 
  geom_col(width = 0.8) + scale_y_continuous(labels = label_comma()) + 
  labs(
         x = "State",
         y = "Total_Sales"
        )
```

```{r, include=TRUE}
ggplot(df_state_ave, aes(x=state_id, y=avg_sales, fill=state_id)) + 
  geom_col(width = 0.7)+ labs(
         x = "State",
         y = "Average_Sales"
        )
```

```{r,include=TRUE}
df_weekday <- df_train %>% group_by(state_id, weekday) %>% summarise(total_sales = sum(sales))
df_weekday <- df_weekday %>%
  group_by(weekday) %>%
  mutate(pct_sales = total_sales / sum(total_sales) * 100)
ggplot(df_weekday, aes(x=weekday, y=total_sales, fill=state_id, label = paste0(round(pct_sales, 1), "%"))) + 
  geom_col(width = 0.7)+ labs(
         x = "State",
         y = "Total_Sales"
        ) + scale_y_continuous(labels = label_comma()) +
  geom_text( 
  size = 2, position = position_stack(vjust = 0.5),colour = "white")
```
